<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\application\FinanceSystem.Application\FinanceSystem.Application.csproj" />
      <ProjectReference Include="..\..\domain\FinanceSystem.Domain\FinanceSystem.Domain.csproj" />
      <ProjectReference Include="..\..\shared\Shared.Autofac\Shared.Autofac.csproj" />
    </ItemGroup>

</Project>
